name = "polar-license-api"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "POLAR_LICENSES"
id = "5ce75d840dba4a6bb0dc8315e8c5cdd5"
preview_id = "9e79fe1d7c3e45d482ffa423e07de397"

# Secrets configurados via: wrangler secret put HMAC_SECRET
# Secrets configurados via: wrangler secret put DASHBOARD_PASSWORD

[triggers]
crons = ["0 4 * * *"]
